openapi: 3.0.0
info:
    title: API Notes
    version: 1.0
tags:
    - notas
paths:
  /notas:
    post:
      summary: Cria uma nova nota
      tags:
        - Notas
      requestBody:
        description: Dados da nova nota
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Notas'
      responses:
        '201':
          description: Nota criada com sucesso
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notas'
    get:
      summary: Lista todas as notas
      tags:
        - Notas
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ArrayOfNotas'
  /notas/{id}:
    get:
      tags:
        - Notas
      parameters: 
        - in: path
          name: id
          type: string
      responses: 
        "200":
          description: Nota encontrada 
          content:
            application/json: 
              schema: 
                $ref: '#/components/schemas/Notas'
        "404": 
          description: Nota não encontrada
    put: 
      tags:
      - Notas
      parameters:
        - in: path
          type: string
          name: id
      requestBody: 
        content: 
          application/json: 
            schema: 
              $ref: '#/components/schemas/Notas'
      responses:
        "200":
          content: 
            application/json:
              schema:
                $ref: '#/components/schemas/Notas'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notas'
    delete:
      tags:
        - Notas
      parameters: 
        - in: path
          type: string
          name: id
      responses:
        "204":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notas'
        "404":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Notas'


components:
  schemas:
    ArrayOfNotas: 
      type: array
      items: 
        $ref: '#/components/schemas/Notas'
    Notas:
      type: object
      properties:
        id:
          type: string
          example: "1" 
        titulo:
          type: string
          example: Tarefa notas dia de hoje
        description:
          type: string
          example: Descrição da tarefa
    Usuarios:
      type: object
      properties:
        email:
          type: string
          example: "email@gmail.com"
        senha:
          type: string
          example: "senha123456_"
        

      